"""initdb

Revision ID: 0e59eaba4bf1
Revises: dae5272c719f
Create Date: 2018-10-27 18:26:14.723900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e59eaba4bf1'
down_revision = 'dae5272c719f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('icon', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=32), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=False),
    sa.Column('xx_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
