"""gender-add

Revision ID: 2ba62b0f2a6d
Revises: 5ed09a7e741b
Create Date: 2018-10-29 17:22:30.310499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba62b0f2a6d'
down_revision = '5ed09a7e741b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
