"""initdb

Revision ID: 3fd18df4e6ca
Revises: c3bf17300f43
Create Date: 2018-10-27 18:28:49.626400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3fd18df4e6ca'
down_revision = 'c3bf17300f43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'xx_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('xx_time', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
