"""gender add default

Revision ID: b3f7c79b73a1
Revises: 05c0dd53491b
Create Date: 2018-10-29 17:16:35.332999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f7c79b73a1'
down_revision = '05c0dd53491b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
